trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/UIs/angular

resources:
  - repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build

    jobs:
      - job: Build
        displayName: Build Angular

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: Use Node.js 24.21.0
            inputs:
              versionSpec: '24.21.0'
              checkLatest: false

          - script: |
              node -v
              npm -v
            displayName: Verify Node.js and npm version

          - task: Npm@1
            displayName: Install Angular CLI
            inputs:
              command: custom
              workingDir: 'src/UIs/angular'
              customCommand: 'install @angular/cli'

          - task: Npm@1
            displayName: npm install
            inputs:
              workingDir: 'src/UIs/angular'

          - task: Npm@1
            displayName: 'npm audit --audit-level=high'
            inputs:
              command: custom
              workingDir: 'src/UIs/angular'
              customCommand: 'audit --audit-level=high'

          - task: Npm@1
            displayName: Run build
            inputs:
              command: custom
              workingDir: 'src/UIs/angular'
              customCommand: 'run build'

          - task: ArchiveFiles@2
            displayName: Archive
            inputs:
              rootFolderOrFile: 'src/UIs/angular/dist/angular'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/angular.$(Build.BuildId).zip'
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@1
            displayName: Publish Pipeline Artifact
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'Angular'
              publishLocation: 'pipeline'