title = "gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "global allow lists"
paths = ['''gitleaks.toml''']
regexes = ['''1079667598840-j2p9duji9qkann88e9j55r6dai3mifa8\.apps\.googleusercontent\.com''']
commits = []

[[rules]]
	id = "BadWords"
	description = "Bad Words"
	regex = '''.*the\s+(hell|heck).*'''

[[rules]]
	id = "Storage.Amazon.AccessKeyID"
	description = "Storage.Amazon.AccessKeyID"
	regex = '''AKI.{5,20}3SQ'''

[[rules]]
	id = "Storage.Amazon.SecretAccessKey"
	description = "Storage.Amazon.SecretAccessKey"
	regex = '''TzX.{5,100}NXl'''
