export const APIEndpoints = {
    PATIENT_REGISTER: "Patient/CreatePatientDetails",
    LOGIN: "Patient/LoginPatient",
    REQUEST_OTP: "Auth/RequestOtp",
    VERIFY_OTP: "Auth/VerifyOtp",
    GET_AVAILABLE_APPOINTMENTS: "Appointment/GetAvailableAppointments",
    GET_SPECIALITIES: "Doctor/GetDoctorList",
    GET_MYAPPOINTMENTS_BY_PATIONT_ID: "Appointment/GetMyAppointmentList/",
    GET_DOCTOR_AVAILABILITIES_BY_DOCTOR_ID: "Doctor/GetDoctorAvailabilities/",
    GET_SECURITY_QUESTIONS: "Auth/GetSecurityQuestionList",
    GET_COUNTRIES: "Location/GetCountriesList",
    GET_STAETES: "Location/GetStatesByCountryList/",
    GET_CITIES: "Location/GetCitiesByStateList/",
    GET_PATIENT_PROFILE_BY_ID: "Patient/GetPatientById/",
    UPDATE_PATIONT_DTAILS: "Patient/UpdatePatientDetails",
    CREATE_APPOINTMENT: "Appointment/CreateAppointment",
    GET_ROLES: "Role/GetRoleList",
    GET_DEPARTMENT: "Department/GetDepartmentList",
    GET_ALL_SPECIALITYLIST: "Doctor/GetDoctorSpecialityList",
    REGISTER_ASSOCIATION: "Associate/RegisterAssociateMaster",
    GET_ROLE_SPECIALITY_AVAILABITY: "Master/GetRoleDepartmentSpecialityList",
    GET_DAYS_OF_WEEKEND: "Master/GetWeekDaysList",
    GET_ASSOCIATE_LIST: "Associate/GetAssociateList",
    CREATE_SCHEDULE_ASSOCIATE: "Associate/CreateAssociateSchedule",
    GET_TIME_SLOTE_BYDOCTOR_ID: "Doctor/GetDoctorTimeSlotById",
    GET_AGE_TYPE: "Master/GetAgeTypeList",
    GET_PROFILE_BASED_ON_PATIENT: "Patient/GetPatientProfileListById/",
    GET_PROFILE_BASED_ON_PROFILEID: "Patient/GetPatientProfileByProfileId/",
    GET_RELATIONSHIP_TYPE: "Master/GetRelationTypeList",
    CANCEL_MY_APPOINTMENT: "Appointment/CancelAppointmentById",
    RESCHEULE_MY_APPOINTMENT: "Appointment/UpdateAppointmentSchedule"

}